[package]
name = "fluent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fluent"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dev-dependencies]
cargo-php = "*"

[dependencies]
# rustler = "0.27.0"
unic-langid = { version = "0.9", features = ["macros"] }
#fluent-langneg = "0.13.0"
fluent-bundle = "0.15"
fluent-syntax = "0.11.0"
lazy_static = "1.4.0"
fluent = "0.16"
ext-php-rs = {version = "0.10.0", features = ["anyhow"]}
intl-memoizer = "0.5.1"

[profile.release]
strip = "debuginfo"
