source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"

# Windows and JRuby do not include zoneinfo files, so bundle the tzinfo-data gem.
gem "tzinfo-data", platforms: [:windows, :jruby]
